
ALL_RELEASES='"7.7", "7.7-aarch64", "7.7-riscv64", "7.8", "7.8-aarch64", "7.8-riscv64", "7.9", "7.9-aarch64", "7.9-riscv64", "7.9-sparc64", "7.9-xfce", "7.9-gnome", "7.9-kde6", "7.9-mate", "7.9-lxqt", "7.9-lumina", "7.9-enlightenment"'


